### ISSUE TITLE
Lisää readme:hen infoa luomuksesta?

### ISSUE THREAD

**Issue by bunchOpaper** [jeesusmies/discvim#1]
Tietoa tästä luomuksesta ja mitä se tekee olisi varsin hyvä.

**Comment by jeesusmies** [comment]
mitä infoo

**Comment by bunchOpaper** [comment]
siis kuten mikä tämä ohjelma on ja mitä se tekee

**Comment by jeesusmies** [comment]
readme.md lukee "Discord Rich Presence (rpc) for Vim, written in C."
